services:
  tripidium:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_TYPE: "${DATABASE_TYPE:-sqlite}"

    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8020:8020

    mem_limit: 256m
    cpus: "0.5"
    pids_limit: 64
